### ISSUE TITLE
Error when i use this plugin

### ISSUE THREAD

**Issue by mario-medina-NTT** [arhill05/backstage-plugin-search-backend-module-azure-devops-wiki#14]
Hello !! 

I have a issue when i try to use this plugins. 

i added resources, add conf in app-config,yaml and set-up backend but when i started backstage process (yarn dev), i got this error 

[backend]: /mnt/c/Temp/backstage/despliegue/backstage-ibercaja/packages/backend/src/index.ts:69
[backend]: backend.add(searchModuleAzureDevopsWikiCollator());
[backend]:                                                ^
[backend]:
[backend]:
[backend]: TypeError: (0 , _backstagepluginsearchbackendmoduleazuredevopswiki.searchModuleAzureDevopsWikiCollator) is not a function
[backend]:     at Object.<anonymous> (/mnt/c/Temp/backstage/despliegue/backstage-ibercaja/packages/backend/src/index.ts:69:48)
[backend]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[backend]:     at Module._compile (/mnt/c/Temp/backstage/despliegue/backstage-ibercaja/node_modules/pirates/lib/index.js:117:24)
[backend]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[backend]:     at Object.newLoader [as .ts] (/mnt/c/Temp/backstage/despliegue/backstage-ibercaja/node_modules/pirates/lib/index.js:121:7)
[backend]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
[backend]:     at Module._load (node:internal/modules/cjs/loader:960:12)
[backend]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
[backend]:     at node:internal/main/run_main_module:23:4

**Comment by mario-medina-NTT** [comment]
Hello. Can you help me with it ? 

Best regards.

**Comment by snaquekiller** [comment]
did you found your solution ? @mario-medina-NTT

**Comment by Woj-Teh** [comment]
BUMP, same issue
